# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# получение объявлений с авторизацией
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a64f9a3f922fbf74b39aa4e11c06a20e7c21093a

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a64f9a3f922fbf74b39aa4e11c06a20e7c21093a

{
  "title": "Carpet IKEA 313",
  "description": "Срочно",
  "status": "OPEN"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/10/
Authorization: Token a64f9a3f922fbf74b39aa4e11c06a20e7c21093a
Content-Type: application/json

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token a64f9a3f922fbf74b39aa4e11c06a20e7c21093a

{
  "title": "Carpet IKEA 310",
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-10-01
Content-Type: application/json
